# Make sure to change the action name here (must be unique).
# Update the rest as needed.
name: 'unique-action-goes-here'
description: 'BRIEF DESCRIPTION OF YOUR ACTION'
branding: # Look at documentation for branding options/requirements. These are my favorites.
  icon: 'book-open'
  color: 'green'
inputs:
  input-one:  
    description: 'Description of input-one'
    required: false
    default: 'default value goes here'
  input-two:
    description: 'Description of input-two'
    required: false
    default: 'default value goes here'
outputs:
  output-one:
    description: 'Description of output-one'
  output-two:
    description: 'Description of output-two'	
jobs:
  run-gource:
    runs-on: ubuntu-latest
    container:
      image : 'Dockerfile'
      options: --user root
    steps:
      - uses: actions/checkout@v4
      - run: |
        gource --version
